// <auto-generated />
using Animatch.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Animatch.Migrations.AnimalManagerDb
{
    [DbContext(typeof(AnimalManagerDbContext))]
    [Migration("20260214190929_MakeBreedTownNullable")]
    partial class MakeBreedTownNullable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Animatch.Models.Animal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Breed")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Species")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Town")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Animals");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Breed = "Немска овчарка",
                            CategoryId = 1,
                            Description = "Търся приятел за дълги разходки в Борисовата градина. Обичам да гоня топка и да тичам до езерото. Имам безкрайно много енергия!",
                            Name = "Рекс",
                            Species = "Куче",
                            Town = "София"
                        },
                        new
                        {
                            Id = 2,
                            Breed = "Златен ретривър",
                            CategoryId = 1,
                            Description = "Супер дружелюбна, обичам всички. Търся куче за игра в парк 'Лаута'. Нося си топка и фризби. Обичам и плуване!",
                            Name = "Бела",
                            Species = "Куче",
                            Town = "Пловдив"
                        },
                        new
                        {
                            Id = 3,
                            Breed = "Джак Ръсел",
                            CategoryId = 1,
                            Description = "Малък, но бърз! Търся приятел за гоненица по плажа. Обичам да ровя в пясъка и да лая на вълните.",
                            Name = "Боби",
                            Species = "Куче",
                            Town = "Варна"
                        },
                        new
                        {
                            Id = 4,
                            Breed = "Хъски",
                            CategoryId = 1,
                            Description = "Обожавам снега! Търся друго хъски или активно куче за планински преходи. Карам и шейна (шегувам се... или не?).",
                            Name = "Луна",
                            Species = "Куче",
                            Town = "Банско"
                        },
                        new
                        {
                            Id = 6,
                            Breed = "Улична принцеса",
                            CategoryId = 2,
                            Description = "Търся коте за приятел. Обичам да гледам птици заедно и да спим на слънце. Нося ти подаръци (мишки).",
                            Name = "Гизда",
                            Species = "Котка",
                            Town = "София"
                        },
                        new
                        {
                            Id = 7,
                            Breed = "Черна",
                            CategoryId = 2,
                            Description = "Търся спокойно коте за приятел. Обичам да се търкалям по топлите плочки и да ям риба. Не съм за врачка!",
                            Name = "Салем",
                            Species = "Котка",
                            Town = "Варна"
                        },
                        new
                        {
                            Id = 9,
                            Breed = "Сиамска",
                            CategoryId = 2,
                            Description = "Елегантна и разговорлива. Търся приятел, който обича да 'разговаря'. Мяукам на различни мелодии!",
                            Name = "Зора",
                            Species = "Котка",
                            Town = "Бургас"
                        },
                        new
                        {
                            Id = 10,
                            Breed = "Африкански сив",
                            CategoryId = 3,
                            Description = "Говоря 50 думи. Търся приятел за разговори и свирене. Ще те науча да казваш 'Здрасти'!",
                            Name = "Жако",
                            Species = "Папагал",
                            Town = "София"
                        },
                        new
                        {
                            Id = 12,
                            Breed = "Бял",
                            CategoryId = 3,
                            Description = "Танцувам! Сериозно, имам ритъм. Търся приятел, който да ме гледа как се клатя. Обичам фъстъци.",
                            Name = "Пио",
                            Species = "Какаду",
                            Town = "Пловдив"
                        },
                        new
                        {
                            Id = 13,
                            Breed = "Джудже",
                            CategoryId = 4,
                            Description = "Търся зайче за приятел. Обичам да скачам, да гриза моркови и да си ровя в сеното. Ще тичаме заедно!",
                            Name = "Хоп",
                            Species = "Заек",
                            Town = "Бургас"
                        },
                        new
                        {
                            Id = 21,
                            Breed = "Брадат дракон",
                            CategoryId = 7,
                            Description = "Търся друг гущер за приятел. Обичам да се пека на лампата и да ям скакалци. Махам си с ръка за поздрав.",
                            Name = "Спайк",
                            Species = "Гущер",
                            Town = "Хасково"
                        },
                        new
                        {
                            Id = 29,
                            Breed = "Див",
                            CategoryId = 11,
                            Description = "Дойдох сам в градината. Търся приятел за вечерни разходки. Ям кучешка храна и съм много сладък.",
                            Name = "Бодльо",
                            Species = "Таралеж",
                            Town = "Ловеч"
                        });
                });

            modelBuilder.Entity("Animatch.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Кучета"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Котки"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Птици"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Зайци"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Гризачи"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Риби"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Влечуги"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Земноводни"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Конe"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Селскостопански"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Диви животни"
                        });
                });

            modelBuilder.Entity("Animatch.Models.Animal", b =>
                {
                    b.HasOne("Animatch.Models.Category", "Category")
                        .WithMany("Animals")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Animatch.Models.Category", b =>
                {
                    b.Navigation("Animals");
                });
#pragma warning restore 612, 618
        }
    }
}
