// <auto-generated />
using System;
using Animatch.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Animatch.Data.Migrations
{
    [DbContext(typeof(AnimalManagerDbContext))]
    [Migration("20260407120032_AddOrganizationProfiles")]
    partial class AddOrganizationProfiles
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Animatch.Models.Animal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Breed")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<double?>("Latitude")
                        .HasColumnType("float");

                    b.Property<double?>("Longitude")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("OwnerId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Species")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Town")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Animals");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Breed = "Немска овчарка",
                            CategoryId = 1,
                            Description = "Търся приятел за дълги разходки в Борисовата градина. Обичам да гоня топка и да тичам до езерото. Имам безкрайно много енергия!",
                            ImageUrl = "https://miau.bg/files/1200x800/nemska-ovcharka2.webp",
                            Name = "Рекс",
                            PhoneNumber = "0881111111",
                            Species = "Куче",
                            Town = "София"
                        },
                        new
                        {
                            Id = 2,
                            Breed = "Златен ретривър",
                            CategoryId = 1,
                            Description = "Супер дружелюбна, обичам всички. Търся куче за игра в парк 'Лаута'. Нося си топка и фризби. Обичам и плуване!",
                            ImageUrl = "https://animoetc.com/cdn/shop/articles/AdobeStock_67967166.jpg?v=1743684891",
                            Name = "Бела",
                            PhoneNumber = "0882222222",
                            Species = "Куче",
                            Town = "Пловдив"
                        },
                        new
                        {
                            Id = 3,
                            Breed = "Джак Ръсел",
                            CategoryId = 1,
                            Description = "Малък, но бърз! Търся приятел за гоненица по плажа. Обичам да ровя в пясъка и да лая на вълните.",
                            ImageUrl = "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSWrp8aabL_Woah30nQChpwR1HbfGZdROmv3ceN8c8sjVTZYdVMnBLQeDZ8dFmG43mC00MIveiakCHE2LSy4bk88kU03YhB9QlgtDLXBw&s=10",
                            Name = "Боби",
                            PhoneNumber = "0883333333",
                            Species = "Куче",
                            Town = "Варна"
                        },
                        new
                        {
                            Id = 4,
                            Breed = "Хъски",
                            CategoryId = 1,
                            Description = "Обожавам снега! Търся друго хъски или активно куче за планински преходи. Карам и шейна (шегувам се... или не?).",
                            ImageUrl = "https://upload.wikimedia.org/wikipedia/commons/a/a3/Black-Magic-Big-Boy.jpg",
                            Name = "Луна",
                            PhoneNumber = "0884444444",
                            Species = "Куче",
                            Town = "Банско"
                        },
                        new
                        {
                            Id = 6,
                            Breed = "Улична принцеса",
                            CategoryId = 2,
                            Description = "Търся коте за приятел. Обичам да гледам птици заедно и да спим на слънце. Нося ти подаръци (мишки).",
                            ImageUrl = "https://m.netinfo.bg/media/images/50202/50202954/624-400-ulichna-kotka.jpg",
                            Name = "Гизда",
                            PhoneNumber = "0885555555",
                            Species = "Котка",
                            Town = "София"
                        },
                        new
                        {
                            Id = 7,
                            Breed = "Черна",
                            CategoryId = 2,
                            Description = "Търся спокойно коте за приятел. Обичам да се търкалям по топлите плочки и да ям риба. Не съм за врачка!",
                            ImageUrl = "https://cdn.marica.bg/images/marica.bg/889/1200_cherna-kotka-spasitelka.jpg",
                            Name = "Салем",
                            PhoneNumber = "0886666666",
                            Species = "Котка",
                            Town = "Варна"
                        },
                        new
                        {
                            Id = 9,
                            Breed = "Сиамска",
                            CategoryId = 2,
                            Description = "Елегантна и разговорлива. Търся приятел, който обича да 'разговаря'. Мяукам на различни мелодии!",
                            ImageUrl = "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS3uIKtBwcbAwSi6o_uzUqgp016-A3D4bswPQ&s",
                            Name = "Зора",
                            PhoneNumber = "0887777777",
                            Species = "Котка",
                            Town = "Бургас"
                        },
                        new
                        {
                            Id = 10,
                            Breed = "Африкански сив",
                            CategoryId = 3,
                            Description = "Говоря 50 думи. Търся приятел за разговори и свирене. Ще те науча да казваш 'Здрасти'!",
                            ImageUrl = "https://static.bnr.bg/gallery/b9/b9ab15c0df0ee58648c4c8d48aa7f9c3.jpg",
                            Name = "Жако",
                            PhoneNumber = "0888888888",
                            Species = "Папагал",
                            Town = "София"
                        },
                        new
                        {
                            Id = 12,
                            Breed = "Бял",
                            CategoryId = 3,
                            Description = "Танцувам! Сериозно, имам ритъм. Търся приятел, който да ме гледа как се клатя. Обичам фъстъци.",
                            ImageUrl = "https://miau.bg/files/1200x800/cacadu.webp",
                            Name = "Пио",
                            PhoneNumber = "0889999999",
                            Species = "Какаду",
                            Town = "Пловдив"
                        },
                        new
                        {
                            Id = 13,
                            Breed = "Джудже",
                            CategoryId = 4,
                            Description = "Търся зайче за приятел. Обичам да скачам, да гриза моркови и да си ровя в сеното. Ще тичаме заедно!",
                            ImageUrl = "https://miau.bg/files/lib/500x350/baby-rabbit-carrot1.webp",
                            Name = "Хоп",
                            PhoneNumber = "0870123456",
                            Species = "Заек",
                            Town = "Бургас"
                        },
                        new
                        {
                            Id = 21,
                            Breed = "Брадат дракон",
                            CategoryId = 7,
                            Description = "Търся друг гущер за приятел. Обичам да се пека на лампата и да ям скакалци. Махам си с ръка за поздрав.",
                            ImageUrl = "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQtyukiUUwuqFgAHnUDE9QkkiUetBo50Uwnzw&s",
                            Name = "Спайк",
                            PhoneNumber = "0871234567",
                            Species = "Гущер",
                            Town = "Хасково"
                        },
                        new
                        {
                            Id = 29,
                            Breed = "Див",
                            CategoryId = 11,
                            Description = "Дойдох сам в градината. Търся приятел за вечерни разходки. Ям кучешка храна и съм много сладък.",
                            ImageUrl = "https://www.kakvoe.eu/wp-content/uploads/2020/06/%D1%82%D0%B0%D1%80%D0%B0%D0%BB%D0%B5%D0%B6.jpeg",
                            Name = "Бодльо",
                            PhoneNumber = "0872345678",
                            Species = "Таралеж",
                            Town = "Ловеч"
                        });
                });

            modelBuilder.Entity("Animatch.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Кучета"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Котки"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Птици"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Зайци"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Гризачи"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Риби"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Влечуги"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Земноводни"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Конe"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Селскостопански"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Диви животни"
                        });
                });

            modelBuilder.Entity("Animatch.Models.Event", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedById")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<double?>("Latitude")
                        .HasColumnType("float");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<double?>("Longitude")
                        .HasColumnType("float");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("Events");
                });

            modelBuilder.Entity("Animatch.Models.OrganizationProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("LogoUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<string>("OrganizationName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Town")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("WebsiteUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("OrganizationProfiles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedOn = new DateTime(2026, 1, 10, 9, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Доброволческа организация за разходки на кучета, временни домове и транспорт до клиники.",
                            LogoUrl = "https://images.unsplash.com/photo-1601758228041-f3b2795255f1?auto=format&fit=crop&w=800&q=80",
                            OrganizationName = "Happy Paws Foundation",
                            PhoneNumber = "0888123456",
                            Town = "Sofia",
                            UserId = "seed-organizer-1",
                            WebsiteUrl = "https://happypaws.example.org"
                        },
                        new
                        {
                            Id = 2,
                            CreatedOn = new DateTime(2026, 1, 15, 11, 30, 0, 0, DateTimeKind.Utc),
                            Description = "Екип, който координира кампании за хранене, кастрация и социализация на бездомни животни.",
                            LogoUrl = "https://images.unsplash.com/photo-1554692936-19b9b7f0f89a?auto=format&fit=crop&w=800&q=80",
                            OrganizationName = "Stray Care Collective",
                            PhoneNumber = "0899765432",
                            Town = "Plovdiv",
                            UserId = "seed-organizer-2",
                            WebsiteUrl = "https://straycare.example.org"
                        });
                });

            modelBuilder.Entity("Animatch.Models.WalkRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AnimalId")
                        .HasColumnType("int");

                    b.Property<string>("Message")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("RequestedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("RequesterId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AnimalId");

                    b.ToTable("WalkRequests");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AnimalId = 1,
                            Message = "Свободен съм в събота следобед за разходка.",
                            RequestedOn = new DateTime(2026, 4, 1, 14, 0, 0, 0, DateTimeKind.Utc),
                            RequesterId = "seed-user-1",
                            Status = 0
                        },
                        new
                        {
                            Id = 2,
                            AnimalId = 2,
                            Message = "Мога да помогна в неделя сутрин.",
                            RequestedOn = new DateTime(2026, 4, 2, 9, 30, 0, 0, DateTimeKind.Utc),
                            RequesterId = "seed-user-2",
                            Status = 1
                        },
                        new
                        {
                            Id = 3,
                            AnimalId = 6,
                            Message = "Искам да участвам и в следващи инициативи.",
                            RequestedOn = new DateTime(2026, 4, 3, 11, 15, 0, 0, DateTimeKind.Utc),
                            RequesterId = "seed-user-3",
                            Status = 2
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Animatch.Models.Animal", b =>
                {
                    b.HasOne("Animatch.Models.Category", "Category")
                        .WithMany("Animals")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Animatch.Models.WalkRequest", b =>
                {
                    b.HasOne("Animatch.Models.Animal", "Animal")
                        .WithMany("WalkRequests")
                        .HasForeignKey("AnimalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Animal");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Animatch.Models.Animal", b =>
                {
                    b.Navigation("WalkRequests");
                });

            modelBuilder.Entity("Animatch.Models.Category", b =>
                {
                    b.Navigation("Animals");
                });
#pragma warning restore 612, 618
        }
    }
}
